name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: Debug runtimes
        run: xcrun simctl list runtimes

      - name: Debug devices
        run: xcrun simctl list devices

      - name: Unit tests
        run: |
          xcodebuild test \
            -project ProjectProposal.xcodeproj \
            -scheme "ProjectProposal-UnitTests" \
            -destination "generic/platform=iOS Simulator"
